### ISSUE TITLE
Signed / Unsigned number

### ISSUE THREAD

**Issue by RobBothof** [maziac/binary-file-viewer#2]
In my custom binary file i have signed values, it would be nice if the parser would support this directly
I solved it now by using:

read(1);
dy = getNumberValue();
if (dy > 128) dy = -256 + dy;
addRow('dirY', dy, 'y direction');

**Comment by maziac** [comment]
Yes, makes sense.
Maybe I can introduce a 'getSignedNumberValue()'.

**Comment by maziac** [comment]
Hi,
can you please install and try the file below.
It has 2 new functions:
- getSignedNumberValue() and
- getSignedDecimalValue() (which adds a hex hover).


[binary-file-viewer-1.5.0-rc1.vsix.zip](https://github.com/maziac/binary-file-viewer/files/9197495/binary-file-viewer-1.5.0-rc1.vsix.zip)

**Comment by RobBothof** [comment]
Hej Maziac,
thanx for the quick reply, thats really cool, I think you singed converstion is 1 decimal off though:

for example:
(4bytes) hex 0008d075 should be 577653 decimal both signed and unsigned in stead of 577652
(8byte example) hex 0000000000D26F07 = 13790983 not 13790982
but the 1 byte 0xFF = -1 is correct!

Thanx for adding this, i think your extension is awesome, this was the only thing missing for me

**Comment by maziac** [comment]
Ooh, I forgot that bit operations are limited to 32 bits in js.
Please try the vsix below:
[binary-file-viewer-1.5.0-rc2.vsix.zip](https://github.com/maziac/binary-file-viewer/files/9212587/binary-file-viewer-1.5.0-rc2.vsix.zip)

**Comment by maziac** [comment]
Does it work now?

**Comment by RobBothof** [comment]
Hi!
it looks good up to 4bytes,
but my 8byte values (Int64) still give problems

I am displaying both
getDecimalValue();
as well as
getSignedDecimalValue();
for each of the following values

                    d.deltaX = -3;
                    d.deltaY = -30;
                    d.deltaXX = -300;
                    d.deltaYY = -3000;
                    d.deltaXY = -30000;
                    d.error =-300000;


![image](https://user-images.githubusercontent.com/10440099/182022230-f4f766aa-840b-4a6a-9fc0-c92542b085ba.png)


Here is the results when values are positive, all ok
                   d.deltaX = 3;
                    d.deltaY = 30;
                    d.deltaXX = 300;
                    d.deltaYY = 3000;
                    d.deltaXY = 30000;
                    d.error =300000;
                    
![image](https://user-images.githubusercontent.com/10440099/182022327-ada16eb8-5a1b-4fc0-8f28-75888918a28a.png)

**Comment by maziac** [comment]
OK, this turned out to be much harder than it seemed in the beginning.
Main problem is that the numbers are only accurate up to 2^53-1.
I.e. 8 byte are 8*8 = 64 bytes and I did it such that first the positive number was calculated and then it was subtracted. But the first number was already wrong (inaccurate).
I now changed the complete decoding for negative numbers.

I have now changed it such that all values that you get through getSignedNumberValue are accurate if they are in range -(2^53-1) < n < 2^53.

But I also changed the functions that return strings. Those functions are accurate now even if the value is much bigger than 2^53. I.e. you can have any number of bits decoded now for strings.

Please try once again.
[binary-file-viewer-1.5.0-rc3.vsix.zip](https://github.com/maziac/binary-file-viewer/files/9252944/binary-file-viewer-1.5.0-rc3.vsix.zip)

**Comment by RobBothof** [comment]
Hi Maziac,
thats awesome!
everything looks good now for me! thanx so much for the effort
greets,
Rob

**Comment by maziac** [comment]
Release 1.5.0 with the fix is out there now.
If you like the extension please consider a review: https://marketplace.visualstudio.com/items?itemName=maziac.binary-file-viewer&ssr=false#review-details
