### ISSUE TITLE
Updating the view

### ISSUE THREAD

**Issue by GiorgioB0nny** [maziac/binary-file-viewer#9]
It seems the button "reload" is useful when you change the parser so that it immediatly updates the view, however if you change the file content the viewer does not responde to the changes so you have to manually close the tab and open it again...  It would be cool to add a feature that set the update to automatic keeping track of content that is changing.

**Comment by maziac** [comment]
Thanks for the suggestion.

There is a limit in the vscode API. The problem is described a little bit here: [FileWatcher](https://github.com/maziac/binary-file-viewer/blob/main/design/overall.md#filewatcher).

vscode captures file changes only if done from within vscode and from within the same vscode window.
I.e. changes that would be done outside from vscode (the normal case for binary files), the API wouldn't notice.
That's the reason why a reload button is implemented.

BTW automatic reload should work in case you are changing the parser file and save it.
But only (vscode restriction) if the parser uses the same vscode window as the view of the content.
